name: asylum_abci_app
author: zarathustra
version: 0.1.0
description: A new service, scaffolded by the Adev cli from zarathustra/asylum_abci_app:0.1.0
aea_version: '>=1.0.0, <2.0.0'
license: apache-2.0
fingerprint: {}
fingerprint_ignore_patterns: []
agent: zarathustra/asylum_abci_app:0.1.0:bafybeiarfswmehmilxwcxjs6q5t7ntedyzpkcadbomply5wzl63sbfn7ee
number_of_agents: 1
deployment:
  agent:
    ports: {}
    volumes: {}
---
public_id: eightballer/http_server:0.1.0:bafybeicp3ubkonolxjgnwgqmaz624qduwzzz74fbjizu77lyvnpo77uv7u
type: connection
config:
  host: 0.0.0.0
  port: 8888
  target_skill_id: zarathustra/asylum_abci_app:0.1.0
