name: git_scraper
author: henrikkv
version: 0.1.0
description: A new service, scaffolded by the Adev cli from henrikkv/git_scraper:0.1.0
aea_version: '>=1.0.0, <2.0.0'
license: apache-2.0
fingerprint: {}
fingerprint_ignore_patterns: []
agent: henrikkv/git_scraper:0.1.0:bafybeicjnedjrbp34fp2z2tjmwqaza5sp2wp3tod5kleasvuoer5inyahi
number_of_agents: 1
deployment:
  agent:
    ports: {}
    volumes: {}
---
public_id: eightballer/http_server:0.1.0:bafybeicp3ubkonolxjgnwgqmaz624qduwzzz74fbjizu77lyvnpo77uv7u
type: connection
config:
  host: 0.0.0.0
  port: 8888
  target_skill_id: henrikkv/demo_fsm_abci_app:0.1.0
