name: asylum_agent
author: eightballer
version: 0.1.0
description: A new service, scaffolded by the Adev cli from eightballer/asylum_agent:0.1.0
aea_version: '>=1.0.0, <2.0.0'
license: apache-2.0
fingerprint: {}
fingerprint_ignore_patterns: []
agent: eightballer/asylum_agent:0.1.0:bafybeia53db4e4f5y67zxigr7zqggftoqdp2r5jsphmkewns2oflaqz6pa
number_of_agents: 1
deployment:
  agent:
    ports: {}
    volumes: {}
---
public_id: eightballer/http_server:0.1.0:bafybeicp3ubkonolxjgnwgqmaz624qduwzzz74fbjizu77lyvnpo77uv7u
type: connection
config:
  host: 0.0.0.0
  port: 8888
  target_skill_id: eightballer/participate_in_abci_app:0.1.0
